service: emission

plugins:
  - serverless-plugin-modularize
  - serverless-iam-roles-per-function

custom:
  stage: ${self:provider.stage}
  modularize:
    glob: 'src/**/*.module.yml' 

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 1
  memorySize: 1536

